name: BestIsYetToCome
favicon: null
layout_spectrum: 0.25119882891885936
typography_spectrum: 0.1312965697143227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07047792477533221
  lightness: 0.645165664376691
  saturation: 0.9709605411626399
  rhythmicContrast: 0.2992599969729781
purpose: []
